### ISSUE TITLE
filecoin 初始化节点

### ISSUE THREAD

**Issue by xwh123** [yangjian102621/blog#1]
请教您一个问题，filecoin 初始化节点 ./go-filecoin init –devnet-user –genesisfile=http://user.kittyhawk.wtf:8020/genesis.car  会报http://user.kittyhawk.wtf:8020  这个地址找不到   这个是不是需要翻墙啊？！

**Comment by yangjian102621** [comment]
这个网络已经关闭了。无法使用了，请直接使用主网或者搭建本地测试网。
